### ISSUE TITLE
Problem with EchoBot example

### ISSUE THREAD

**Issue by blopa** [carpedm20/fbchat#106]
Hi!

I was trying to use the EchoBot example, but I'm getting an error:

`(<type 'exceptions.TypeError'>, TypeError('on_message() takes exactly 6 arguments (7 given)',), <traceback object at 0x0000000003A8D088>)`

I just copied and pasted the code from example, login was successfully, this problem happens everytime I got a message.

Thank you

**Comment by milo123milo** [comment]
try to update fbchat
`pip install --upgrade fbchat`

**Comment by madsmtm** [comment]
Yeah, this is my fault, turns out python doesn't work the way i expected (Too much C++, i guess ;) ), when it comes to overriding functions. #108 should fix this

**Comment by blopa** [comment]
Hello guys!

@milo123milo, I tried that, and it says I already have the latest version, v0.7.1.

@madsmtm Thank you. I tried pulling the latest version from this repository, but I'm not sure if this version is overwritting my pip installation or not, because I tried the echobot again and I'm still having the same error.
